### PR TITLE
fix(angular): add comma after each host content

### PR DESCRIPTION
**Pull request by rahul-rautwar**
Raised a PR to fix the below issue:
https://github.com/ionic-team/stencil-ds-output-targets/issues/165 
Fixes: [165](https://github.com/ionic-team/stencil-ds-output-targets/issues/165)

### CODE REVIEW

**Comment by rahul-rautwar** [comment]
@adamdbradley can someone from your team look into this?

**Comment by nphyatt** [comment]
@rahul-rautwar Thanks for the PR! Would you mind adding a quick test so that we can see the intended functionality and ensure it continues to work going forward?

**Comment by rahul-rautwar** [comment]
@nphyatt I didn't find any spec/test file for `generate-value-accessors.ts`. If there had been a test file, I would have updated the test cases while raising the PR itself.

**Comment by nphyatt** [comment]
@rahul-rautwar I've put up PR #167 that includes your fix & adds tests for it in order to make sure there are no regressions going forward. I'm closing this PR in favor of that one.

**Comment by rahul-rautwar** [comment]
@nphyatt Thank you 👍

**Comment by nphyatt** [comment]
@rahul-rautwar @stencil/angular-output-target v0.0.7 is now available on NPM with the fix.

**Pull request closed without merging**
