### PR TITLE
fix(output-react): default loader directory

### PR DESCRIPTION
**Pull request by ps011**
https://github.com/ionic-team/stencil-ds-plugins/issues/49

### CODE REVIEW

**Comment by ps011** [comment]
@manucorporat @adamdbradley do I need to add anything else in this ?

**Comment by ps011** [comment]
@jthoms1 @manucorporat anything else required from my side? I'm blocked because of this.

**Comment by adamdbradley** [comment]
Thanks, and we'll also make some updates so it's reading any custom loader paths they may have configured in the `dist` output target. Thanks

**Comment by ps011** [comment]
When can I expect this to be released @adamdbradley ?

**Pull request merged**
