### PR TITLE
fix(react): improve resolving component types

### PR DESCRIPTION
**Pull request by dwirz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally for affected output targets
- [x] Tests (`npm test`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There are still some cases where resolving the correct types fails, which results in warnings and, occasionally, incorrectly rendered content.

Issue URL: #561 

## What is the new behavior?

Resolve component types correctly also for nested and lazy components.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I’ve added some new components and new tests to the Next.js example project to verify that the generated HTML includes the expected Declarative Shadow DOM.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@dwirz thanks for raising the PR, let me take a look at this after Christmas 😉

**Comment by dwirz** [comment]
No worries, thanks a lot for your time and review. Happy Christmas 🙂 

btw somehow the `toMatchSnapshot` does fail in the CI but was working locally, do I miss something?

**Comment by christian-bromann** [comment]
> btw somehow the `toMatchSnapshot` does fail in the CI but was working locally, do I miss something?

No, this may be related to https://github.com/webdriverio/webdriverio/issues/14011

**Comment by dwirz** [comment]
@christian-bromann My bad! I renamed the test but forgot to update the snapshots, so the names ended up misaligned. 🤦‍♂️

**Review by christian-bromann — APPROVED** [review]
Awesome stuff, thanks so much 🙏

**Pull request merged**
