### PR TITLE
make angular-output-target work with angular production builds

### PR DESCRIPTION
**Pull request by mixer2**
If the angular wrappers are included in an angular application compiled with aot and buildOptimizer, the buildOptimizer will remove the proxyInputs logic since it's not really part of component. It just thinks it's unused code and tries to make the bundle as small as possible.
To prevent the code from getting removed the proxy inputs can be added via ts class annotation. Those are untouched by the build optimizer, as long as they annotate a component class.

### CODE REVIEW

**Comment by misterjojo** [comment]
Hi all,

Any idea when this PR will be merged ? I'm facing the same issue on my project, everything works fine until i compile with iot +buildOptimizer.

**Comment by dopsonbr** [comment]
Any update on this?

**Comment by hypery2k** [comment]
any chance to get this merged?

**Comment by jthoms1** [comment]
I believe that this is now obsolute because of PR https://github.com/ionic-team/stencil/pull/2033.

**Pull request closed without merging**
