### PR TITLE
fix: check for type prop on resolved type and use it as type

### PR DESCRIPTION
**Pull request by dwirz**
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally for affected output targets
- [x] Tests (`npm test`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue URL: #561 

## What is the new behavior?

See Issue.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

None.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@dwirz how about we merge this change into #562 ?

**Comment by christian-bromann** [comment]
Maybe you missed to commit everything because I only see comment changes here?

**Comment by dwirz** [comment]
@christian-bromann You’re right, I forgot to undo the commented code I added for testing. 🤦 Regarding merging this into the other PR: this change, as mentioned in the linked issue, is just a quick fix to solve the current problem without rewriting the entire resolve function. This change is already included in #562.

That said, it’s up to you/the team to decide which change to include. 🙂 I’m confident that #562 works for the cases within the repo, but since there aren’t as many tests as in the Stencil repo, I’m not sure if I missed something. That’s why I provided the current PR—it’s less “error-prone” but might miss other cases. Does that make sense?

**Comment by christian-bromann** [comment]
Totally makes sense! I very like the implementation improvements you made in https://github.com/ionic-team/stencil-ds-output-targets/pull/562 so I will go ahead and merge this one. In regards to testing, yes, we absolutely need to cover more cases and improve the coverage. Any contribution in that direction would be much appreciated.

Thanks a lot for getting involved ❤️

**Pull request closed without merging**
