### PR TITLE
fix(angular-output-target): output target types and config options

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally for affected output targets
- [x] Tests (`npm test`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

N/A

## What is the new behavior?

- Removes `directivesProxyFile` from the output target options.
  - Developers will receive an error message with the new property name.
- Marks `componentCorePackage` as a required property (it is required in the implementation).
- Fixes typo in `valueAccessorConfig` vs. `valueAccessorConfigs` option (enforced types to avoid this problem in the future).

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

`directivesProxyFile` has been removed. Developers will need to replace this option in their output target with `proxyDeclarationFile`.

### CODE REVIEW

**Comment by sean-perkins** [comment]
This should be the last PR (outside of the documentation PR I am working on next) related to the SCAM work. On the off chance there is another PR, it would be a smaller bug fix from testing with the dev-build.

**Review by rwaskiewicz — CHANGES_REQUESTED** [review]
One small nit from a code standpoint.

**Review by rwaskiewicz — APPROVED** [review]

**Review by liamdebeasi — APPROVED** [review]
Any thoughts on how we can better expose this breaking change? Maybe a BREAKING.md file? Or would mentioning it in the release notes be good enough?

**Comment by sean-perkins** [comment]
@liamdebeasi I like the idea of including a `BREAKING.md` file, especially since our changelog is currently unmanaged.

**Pull request merged**
