### PR TITLE
feat(react-output-target): add customElementsDir configuration option

### LINKED ISSUE #457: [react-output-target] bug: generated components.ts using absolute paths in an Nx monorepo
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.20.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.6.0

### Current Behavior

After the latest changes on [this PR](https://github.com/ionic-team/stencil-ds-output-targets/pull/452), it seems that the `@stencil/react-output-target` package generates the `components.ts` file using absolute paths when the project structure is a monorepo environment with NX.

image

> [!IMPORTANT]
> **Please, note that this issue does not occur with the previous version** of `@stencil/react-output-target` v0.5.3.

### Expected Behavior

The `@stencil/react-output-target` package is designed to generate the `components.ts` file with the correct paths.

### Steps to Reproduce

Follow the steps described in the **Issue 2** of the reproduction code below

### Code Reproduction URL

https://github.com/dgonzalezr/nx-stencil

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally for affected output targets
- [x] Tests (`npm test`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Environments using absolute paths run into issues with using the calculated path for the custom elements directory based on the `dist-custom-elements` configuration.

Issue URL: Resolves #457

## What is the new behavior?

- Re-adds the `customElementsDir` configuration for developers to manually override the path as needed in their environment.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev-build: `@stencil/react-output-target@0.0.1-dev.11724437043.1612ee70`

### CODE REVIEW

**Comment by dgonzalezr** [comment]
I just tested the dev-build on the same repo as the original issue, and I can confirm that it is now working as expected with the `customElementsDir` configuration option.

CleanShot 2024-08-25 at 13 52 03@2x

**Review by tanner-reits — APPROVED** [review]

**Review by christian-bromann — APPROVED** [review]

**Comment by mjsorribas** [comment]
Hi! Can you please add documentation about the implementation in the stencil configuration file?
I have something like this :
outputTargets: [
		reactOutputTarget({
			stencilPackageName: "@mypackage/my-lib-components",
			outDir: "../my-lib-components-react/src/",
			customElementsDir: "@mypackage/my-lib-components"
		}),
I am not clear about whether this is the correct configuration.
Thanks!

**Comment by christian-bromann** [comment]
> The version 0.6.0 and 0.7.0 generate a break in the build.

Our team currently doesn't apply strict semver on these output targets as we haven't released a v1.0 just yet.

We have recently updated the [docs around the React Output Target](https://stenciljs.com/docs/react#adding-the-react-output-target). Mind taking a look and help us identify what is missing?

**Comment by christian-bromann** [comment]
> [ ERROR ] Error: The 'react-output-target' requires the 'dist-custom-elements'
> output target to have 'externalRuntime: false' set in its

We recommend this setup when integrating your Stencil components into a React project. With the new release this has been enforced.

**Pull request merged**
