### PR TITLE
feat(react-output-target): generate functional components and ES modules

### LINKED ISSUE #255: bug: Tree shaking is not working with React output target
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

2.9

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.3.1

### Current Behavior

Hi, I am using react output target to generate a tree shakable bundle of the React components. Stencil config file below.

```   reactOutputTarget({
      componentCorePackage: `@freshworks/${packageName}`, // name in the package.json should be used
      proxiesFile: './crayons-react/components.ts',
      customElementsDir: 'dist/components',
      includeImportCustomElements: true,
    }) 
```
    
**Usage in the consuming app,** 
import { FwButton } from "@freshworks/crayons/react";

when I run npm run build, in the main script that gets bundled, I see code for all the components added and tree shaking is not working.

### Expected Behavior

Tree shaking should work fine.

### Steps to Reproduce

Stencil config file below.

```  reactOutputTarget({
      componentCorePackage: `@freshworks/${packageName}`, // name in the package.json should be used
      proxiesFile: './crayons-react/components.ts',
      customElementsDir: 'dist/components',
      includeImportCustomElements: true,
    })
```
    
**Usage in the consuming CRA app,** 
import { FwButton } from "@freshworks/crayons/react";

when I run npm run build, in the main script that gets bundled, I see code for all the components added and tree shaking is not working.

### Code Reproduction URL

https://github.com/freshworks/crayons/

### Additional Information

The issue is because all the components are imported and exported from the same file. 

``` export const FwAccordion = /*@__PURE__*/createReactComponent<JSX.FwAccordion, HTMLFwAccordionElement>('fw-accordion', undefined, undefined, defineFwAccordion);
export const FwAccordionBody = /*@__PURE__*/createReactComponent<JSX.FwAccordionBody, HTMLFwAccordionBodyElement>('fw-accordion-body', undefined, undefined, defineFwAccordionBody);
```

Fix - https://github.com/arvindanta/stencil-react-wrapper/blob/master/src/output-react.ts#L155

I had solved this by forking this repo and exported each component in a separate file and they are just imported here. Can we please check on this ?

component.ts
```
import { FwAccordion } from './FwAccordion'
import { FwAccordionBody } from './FwAccordionBody'
```

FwAccordion file
```
// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@freshworks/crayons/dist/components';

import { FwAccordion as FwAccordionCmp, defineCustomElement as defineCustomElementFwAccordion } from '@freshworks/crayons/dist/components/fw-accordion.js';
export const FwAccordion = /*@__PURE__*/createReactComponent<JSX.FwAccordion, HTMLFwAccordionElement>('fw-accordion', undefined, undefined, FwAccordionCmp, defineCustomElementFwAccordion);

```

_No response_

### LINKED ISSUE #361: Polyfills are included when includeDefineCustomElements is true in config, even when includePolyfills is false.
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Polyfills are included when `includeDefineCustomElements` is `true` in config, even when `includePolyfills` is `false`.

**Expected behavior:**
the /dist/esm/polyfiles/core-js.js and /dist/esm/polyfills/dom.js files would not be included in the build of a consuming application

**Steps to reproduce:**
- Use the following config: 
```tsx
    reactOutputTarget({
      componentCorePackage: '@wclib/core',
      proxiesFile: '../wclib-react/src/components.ts',
      includeDefineCustomElements: true,
      includePolyfills: false,
    })
```
- Use a component in a fresh create-react-app
- build the CRA bundle
- use `source-map-explorer` to find out what's causing the ~100KB bloat
- discover that it's polyfills from stencil:
image

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally for affected output targets
- [x] Tests (`npm test`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue URL: resolves #255, #89, #404, closes #361, #243,  #198, #88, #359, #148, #138

The issues linked are either resolved from these changes or no longer apply due to these changes. I've tried to separate them as such to help future maintainers separate why so many tickets are attached to this PR. 

### React Output Target
- Rewrites the react output target to standardize around the custom elements output target
- Adds support for generating separate ES modules for each component
- Component wrappers are generated as functional components
- Experimental option to generate component wrappers with `use client;` directive.
- Adds wdio tests for the test application

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

Latest dev-build (2024-05-22): `0.0.1-dev.11716386285.1a6265fd`

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by sean-perkins** [comment]
I looked into 1. The use of `imports` and `exports` in the `package.json` requires a feature available in TypeScript 5, `moduleResolution: "bundler"`. When enabled, this also requires `module: "esnext"` to be configured. I will make sure these details are included in both the repository README and update the documentation updates as I don't think it will be commonly known by developers. 

Reflecting more on our conversation with 2, I am less confident if we should clear the directory or files. The goal is to co-locate your generated component wrappers alongside any potential React-only components/component implementations. Clearing the directory between builds would prevent this. If we wanted to do this is a less destructive way, we would need to keep a generated output of what the react-output-target generated somewhere and parse that to determine what files are "owned" by the output target and are safe to delete between builds. This could be a cool feature, but I would recommend we track that as follow-up scope. 

When testing I also observed the new output no longer uses the syntax sugar for bundlers like webpack for marking functions as pure. I will see what the work effort to generate this through ts-morph is.

**Comment by sean-perkins** [comment]
We received some feedback from testing, there is two different underlying issues with more complex type usages on custom events. I am going to try reproducing locally and update the output target to account for those. 

It is possible for it to use a reference as value instead of `typeof` and it does not import all type references used. The demo code provides includes the use of nested namespaces.

**Comment by sean-perkins** [comment]
Identified the issues with the PR. I was incorrectly using the resolved (inline) type instead of directly leveraging the original type references that Stencil re-exports and specifies on the events metadata. This ended up resolving both issues.

**Review by tanner-reits — APPROVED** [review]
LGTM!

**Review by thetaPC — APPROVED** [review]
LGTM, tested on Ionic Framework and Stencil DS Output Targets.

**Comment by TRMW** [comment]
> I looked into 1. The use of `imports` and `exports` in the `package.json` requires a feature available in TypeScript 5, `moduleResolution: "bundler"`. When enabled, this also requires `module: "esnext"` to be configured. I will make sure these details are included in both the repository README and update the documentation updates as I don't think it will be commonly known by developers.

I just ran into this issue trying to update to the latest version of this package. Would be great to document this in the README. :)

**Comment by sean-perkins** [comment]
@TRMW these details are documented in the README: https://github.com/ionic-team/stencil-ds-output-targets/tree/main/packages/react-output-target and on the official docs: https://stenciljs.com/docs/react#step-2---react-component-library

**Comment by TRMW** [comment]
@sean-perkins I just realized this! Thanks for the help though!

**Pull request merged**
