### PR TITLE
chore: restructure packages

### PR DESCRIPTION
**Pull request by christian-bromann**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally for affected output targets
- [x] Tests (`npm test`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): restructuring of files

## What is the current behavior?

It is a bit confusing to have the example project next to our output target packages.

## What is the new behavior?

A little restructuring to make the responsibilities more clear:
Screenshot 2024-10-09 at 3 44 45 PM

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

n/a

### CODE REVIEW

**Comment by thetaPC** [comment]
I have no issues with this reorganization. Ping me once the checks are passing.

**Review by tanner-reits — CHANGES_REQUESTED** [review]
`pnpm run build` doesn't build the Next app (due to script naming), but also results in a build failure when changed 

> ./src/app/components.server.ts:33:9
      Type error: Type 'typeof React' is missing the following properties from type 'typeof import("/Users/tannerreits/Documents/repos/stencil-ds-output-targets/node_modules/.pnpm/@types+react@18.3.11/node_modules/@types/react/index.d.ts")': use, createServerContext, cache, unstable_useCacheRefresh, and 6 more.

**Comment by christian-bromann** [comment]
> `pnpm run build` doesn't build the Next app (due to script naming)

I've updated the script to include building the Next.js application as part of the main build.

> Should this still exist? Don't think it's serving a purpose here

The error is a result of a React type mismatch between the React version from the `@lit/react` project and the version used in the Next.js app. I tried to enhance. the `Options` type with another generic to pass the original React type along, unfortunately I wasn't successful. I ended up just adding a `ts-ignore` on top of the line. This should be sufficient as I don't expect a scenario where the React version mismatch impacts how the component is being rendered as we pass along the right React object, it is just the type that is not passed along.

**Comment by christian-bromann** [comment]
I will move ahead and merge this as I realised when merging the upstream PRs that the changeset now has become to large. Happy to address any further concerns in a separate PR.

**Pull request merged**
